server:
  port: 80
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
  redis:
    database: 0
    port: 6379
    host: geniusay.com
    password:
