server:
  port: 80
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - path = /user/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - path = /comment/**
        - id: feed-service
          uri: lb//feed-service
          predicates:
            - path = /feed/**
        - id: im
          uri: lb//im-service
          predicates:
            - path = /im/**
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:geniussbg.cn:8848}
      username: ${NACOS_SERVER_USER:nacos}
      password: ${NACOS_SERVER_PASSWORD:keKEaiai5201314}
      discovery:
        ip: ${SERVER_ADDR:geniussbg.cn}




