server:
  port: ${SERVER_PORT:8008}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}


review:
  logger:
    handler: ${LOGGER_HANDLER:sl4j}
  examine:
    handler: ${EXAMINE_HANDLER:qiniu}
  qiniu:
    sk: WgwuUrvEnjBOLPnMe8mYvi3S8IxTzIN1qp22bGqM
    ak: 4rdOegZZUy1gurS8qMMI7AZN12p0p62vIaaH08QR
