server:
  port: 8007
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://geniussbg.cn0000:3306/seven-cow-cloud?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: genius_server_0704
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: geniusay.com # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: PublishApplication
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:geniussbg.cn:8848}
      username: ${NACOS_SERVER_USER:nacos}
      password: ${NACOS_SERVER_PASSWORD:keKEaiai5201314}
      config:
        file-extension: yaml
      discovery:
        ip: ${SERVER_ADDR:geniussbg.cn}
#mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
